import React, { useState, useRef } from 'react';
import axios from 'axios';
import '../css/style.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faUser } from '@fortawesome/free-solid-svg-icons';

function InviteUser() {
  const formRef = useRef(null);

  const [formData, setFormData] = useState({
    FullName: '',
    Email: '',
    Password: '',
    UserRole: '',
    University: '',
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      // Make a POST request to your registration API
      const response = await axios.post('http://localhost:5000/invite-user', formData);
      console.log(formData)
      if (response.data.message === 'User Invited') {
        // Registration was successful
        console.log('Invite successful');
       //refresh form after submit
        setFormData({
          FullName: '',
          Email: '',
          Password: '',
          UserRole: '',
          University: '',
        });
        //formRef.current.reset(); // Reset the form

      } else {
        // Handle registration errors
        console.error('Invite failed');
      }
    } catch (error) {
      console.error('Error:', error);
    }
  };


  return (
    <div>
      <form className="user-invite-form" onSubmit={handleSubmit}>
        <div className="form-row">
          <label className="form-label">Full Name</label>
          <input type="text" name="FullName" placeholder="Invitee's Name" className="input-text" value={formData.FullName} onChange={handleChange} />
        </div>
        <div className="form-row">
          <label className="form-label">Email</label>
          <input type="Email" name="Email" placeholder="Invitee's Email" className="input-text" value={formData.Email} onChange={handleChange} />
        </div>
        <div className="form-row">
          <label className="form-label">Password</label>
          <input type="password" name="Password" placeholder="Autogenerated Password" className="input-text" value={formData.Password} onChange={handleChange} />
        </div>
        <div className="form-row">
          <label className="form-label">User Role</label>
          <select name="UserRole" className="input-select" value={formData.UserRole} onChange={handleChange}>
            <option value="">Select a role</option>
            <option value="Intern">Intern</option>
            <option value="Admin">Admin</option>
            <option value="Evaluator">Evaluator</option>
            <option value="Mentor">Mentor</option>
            <option value="Management">Management</option>
          </select>
        </div>
        {formData.UserRole === 'Intern' && (
          <div>
            <div className="form-row">
              <label className="form-label">University</label>
              <input
                type="text"
                name="University"
                value={formData.University}
                onChange={handleChange}
                placeholder="Invitee's University"
                className="input-text"
              />
            </div>
          </div>
        )}
        <div>
          <button className="button-primary invite-button" type="submit"><FontAwesomeIcon icon={faUser} className="invite-button-icon"/>Invite User</button>
        </div>
      </form>
    </div>
  );
}



export default InviteUser;
